#
###################################
# Site wide configuration
####################################
#
title: Maty's Notes
email: email@matyasprokop.com
description: Random notes about Network Automation, DevOps, Linux and SDN
url: https://blog.matyasprokop.com


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
show_drafts: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Maty's Notes
  #avatar: leonids-logo.png
  #job: "A jekyll theme"
  bio: "Random notes about Network Automation, DevOps, Linux and SDN"
  email: email@matyasprokop.com
  disqus-shortname: blog-matyasprokop-com
  gitlab: git.matyasprokop.com/mprokop
  twitter: maty0609
  facebook: #username
  google:
    plus: #username
    analytics: G-88LJB1E0QX
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: matyasprokop
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
